### ISSUE TITLE
Upgrade pillow

### ISSUE THREAD

**Issue by AdamGleave** [HumanCompatibleAI/interactive-behaviour-design#1]
@mrahtz is it OK to upgrade Pillow to >=6.2.0? GitHub keeps pestering me about a vulnerability in earlier versions. I know we're not going to read malicious input here but it seems worth upgrading if it won't break anything.

**Comment by mrahtz** [comment]
This is difficult with pipenv last time I checked; you can't update one package without updating all the rest too (and you can't do it manually because all the hashes are checked). I've dismissed the alerts with "risk tolerable to this project".
